package aclrule

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func aclruleDataSourceSchema() schema.Schema {
	return schema.Schema{
		Description: "Data source to retrieve information about a ACL Rule.",
		Attributes: map[string]schema.Attribute{
			"action": schema.StringAttribute{
				Computed:            true,
				Description:         "Action can be [Allow Block]. Minimum length =  4 Maximum length =  5",
				MarkdownDescription: "Action can be [Allow Block]. Minimum length =  4 Maximum length =  5",
			},
			"dst_port": schema.StringAttribute{
				Computed:            true,
				Description:         "Enable external authentication.",
				MarkdownDescription: "Enable external authentication.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				Description:         "Rule Name. Minimum length =  1 Maximum length =  128",
				MarkdownDescription: "Rule Name. Minimum length =  1 Maximum length =  128",
			},
			"priority": schema.Int64Attribute{
				Computed:            true,
				Description:         "Priority. Minimum value =  1 Maximum value =  ",
				MarkdownDescription: "Priority. Minimum value =  1 Maximum value =  ",
			},
			"protocol": schema.StringAttribute{
				Computed:            true,
				Description:         "IP Protocol. The allowed values are [TCP UDP ICMP ANY]. Minimum length =  3 Maximum length =  4",
				MarkdownDescription: "IP Protocol. The allowed values are [TCP UDP ICMP ANY]. Minimum length =  3 Maximum length =  4",
			},
			"src_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "Source IP Address or Subnet. Minimum length =  3 Maximum length =  128",
				MarkdownDescription: "Source IP Address or Subnet. Minimum length =  3 Maximum length =  128",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of this resource, it is the random string generated by remote SDX.",
			},
		},
	}
}
