package smtp_server

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func smtpServerDataSourceSchema() schema.Schema {
	return schema.Schema{
		Description: "Data source to retrieve information about a SMTP server.",
		Attributes: map[string]schema.Attribute{
			"is_auth": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is authentication enabled for this smtp server.",
				MarkdownDescription: "Is authentication enabled for this smtp server.",
			},
			"is_ssl": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is this smtp server is SSL support configured..",
				MarkdownDescription: "Is this smtp server is SSL support configured..",
			},
			"password": schema.StringAttribute{
				Computed:            true,
				Description:         "Password for the smtp server. Maximum length =  128",
				MarkdownDescription: "Password for the smtp server. Maximum length =  128",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "SMTP Server port address.. Minimum value =  1 Maximum value =  ",
				MarkdownDescription: "SMTP Server port address.. Minimum value =  1 Maximum value =  ",
			},
			"sender_mail_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Email Address from which email is to be sent.",
				MarkdownDescription: "Email Address from which email is to be sent.",
			},
			"server_name": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				Description:         "SMTP server name. Minimum length =  1 Maximum length =  128",
				MarkdownDescription: "SMTP server name. Minimum length =  1 Maximum length =  128",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "Username for the smtp server. Maximum length =  128",
				MarkdownDescription: "Username for the smtp server. Maximum length =  128",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of this resource, it is the random string generated by remote SDX.",
			},
		},
	}
}
