package static_route

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func staticRouteDataSourceSchema() schema.Schema {
	return schema.Schema{
		Description: "Data source to retrieve information about a static route.",
		Attributes: map[string]schema.Attribute{
			"gateway": schema.StringAttribute{
				Computed:            true,
				Description:         "Gateway for route addition.",
				MarkdownDescription: "Gateway for route addition.",
			},
			"netmask": schema.StringAttribute{
				Computed:            true,
				Description:         "netmask for route addition.",
				MarkdownDescription: "netmask for route addition.",
			},
			"network": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				Description:         "network for route addition.",
				MarkdownDescription: "network for route addition.",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of this resource, it is the random string generated by remote SDX.",
			},
		},
	}
}
