// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ns_save_config

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
)

func nsSaveConfigResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "Configuration for Save configuration on NetScaler ADC resource.",
		Attributes: map[string]schema.Attribute{
			"ns_ip_address_arr": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
				// We have below code insted of ForceNew
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
				Description:         "List of NetScaler ADC IP Address. Minimum length =  1 Maximum length =  1024",
				MarkdownDescription: "List of NetScaler ADC IP Address. Minimum length =  1 Maximum length =  1024",
			},
			"id": schema.StringAttribute{
				Computed: true,
				Optional: true,
			},
		},
	}
}

type nsSaveConfigModel struct {
	NsIpAddressArr types.List   `tfsdk:"ns_ip_address_arr"`
	Id             types.String `tfsdk:"id"`
}

type nsSaveConfigReq struct {
	NsIpAddressArr []string `json:"ns_ip_address_arr,omitempty"`
}
